name: laporin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.8.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  convex_bottom_bar: ^3.2.0
  intl: ^0.17.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  syncfusion_flutter_datepicker: ^21.1.37
  image_picker: ^0.8.7+1
  timezone: ^0.9.1
  file_picker: ^5.2.6
  video_player: ^2.6.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/